// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW0ECLp3s2Y816TiNtIZiPPSbeP4ij8W8',
    appId: '1:530543737782:web:af07c1ab9a1ab5cd439f17',
    messagingSenderId: '530543737782',
    projectId: 'taplus-app-14d0a',
    authDomain: 'taplus-app-14d0a.firebaseapp.com',
    storageBucket: 'taplus-app-14d0a.appspot.com',
    measurementId: 'G-C2TQP6DXKR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADedAStw67yFwTtRZsNBk6LdGNSXLnmeY',
    appId: '1:530543737782:android:68819a276f5d3ca0439f17',
    messagingSenderId: '530543737782',
    projectId: 'taplus-app-14d0a',
    storageBucket: 'taplus-app-14d0a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoXvlO_kkZPWodeMKuOwiXpB83vIQCJeg',
    appId: '1:530543737782:ios:1fb8b7c7df31b606439f17',
    messagingSenderId: '530543737782',
    projectId: 'taplus-app-14d0a',
    storageBucket: 'taplus-app-14d0a.appspot.com',
    iosClientId: '530543737782-bschl5n85thqqtt41f0q29n2tlh520em.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaPlus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoXvlO_kkZPWodeMKuOwiXpB83vIQCJeg',
    appId: '1:530543737782:ios:1fb8b7c7df31b606439f17',
    messagingSenderId: '530543737782',
    projectId: 'taplus-app-14d0a',
    storageBucket: 'taplus-app-14d0a.appspot.com',
    iosClientId: '530543737782-bschl5n85thqqtt41f0q29n2tlh520em.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaPlus',
  );
}
